# Generated by Django 6.0.4 on 2026-06-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_notificacion_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('PAGO_REGISTRADO', 'Pago Registrado'), ('PAGO_APROBADO', 'Pago Aprobado'), ('PAGO_RECHAZADO', 'Pago Rechazado'), ('SISTEMA', 'Alerta de Sistema')], default='SISTEMA', max_length=50),
        ),
    ]
