# Generated by Django 6.0.4 on 2026-06-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='ruta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
