# Generated by Django 6.0.4 on 2026-05-21 05:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0005_alter_apoderado_dni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('CUOTA_INGRESO', 'Cuota de Ingreso (Único)'), ('MATRICULA', 'Matrícula (Anual)'), ('PENSION', 'Pensión (Mensual)'), ('OTROS', 'Otros Pagos')], default='PENSION', max_length=20)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja Diaria',
                'verbose_name_plural': 'Control de Cajas',
            },
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_adicional', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagado', 'Pagado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='estudiantes.estudiante')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pagos.conceptopago')),
            ],
            options={
                'verbose_name': 'Recibo de Cobranza',
                'verbose_name_plural': 'Recibos de Cobranza',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total_entregado', models.DecimalField(decimal_places=2, help_text='Total de dinero recibido en el voucher/efectivo', max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Yape', 'Yape'), ('Plin', 'Plin'), ('Transferencia', 'Transferencia'), ('Depósito', 'Depósito')], default='Efectivo', max_length=20)),
                ('numero_operacion', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('comprobante_img', models.ImageField(blank=True, null=True, upload_to='vouchers/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='estudiantes.estudiante')),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pagos.caja')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
            },
        ),
        migrations.CreateModel(
            name='PagoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='pagos.deuda')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='pagos.pago')),
            ],
            options={
                'verbose_name': 'Asignación de Pago',
                'verbose_name_plural': 'Asignaciones de Pago',
            },
        ),
    ]
