# Generated by Django 6.0.4 on 2026-05-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deuda',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deuda',
            name='detalle_adicional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
