# Generated by Django 6.0.4 on 2026-06-06 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0006_periodoacademico_matricula_periodo_academico'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='periodo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='matriculas.periodoacademico'),
        ),
    ]
