# Generated by Django 6.0.4 on 2026-06-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_deuda_periodo_academico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deuda',
            options={'ordering': ['id'], 'verbose_name': 'Recibo de Cobranza', 'verbose_name_plural': 'Recibos de Cobranza'},
        ),
    ]
