# Generated by Django 6.0.4 on 2026-06-08 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_banco_pago_estado_pago_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='deuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_reportados', to='pagos.deuda'),
        ),
    ]
