# Generated by Django 6.0.4 on 2026-06-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_pago_deuda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='Jardín Nuestra Señora de Montserrat', max_length=150)),
                ('titular_yape', models.CharField(max_length=150)),
                ('numero_yape', models.CharField(max_length=20)),
                ('qr_yape', models.ImageField(blank=True, null=True, upload_to='configuracion_pagos/')),
                ('titular_plin', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_plin', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_plin', models.ImageField(blank=True, null=True, upload_to='configuracion_pagos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Pago',
                'verbose_name_plural': 'Configuraciones de Pago',
            },
        ),
    ]
