# Generated by Django 6.0.4 on 2026-08-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_configuracionpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionpago',
            name='qr_plin_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionpago',
            name='qr_yape_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionpago',
            name='qr_plin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionpago',
            name='qr_yape',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante_img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
