# Generated by Django 6.0.4 on 2026-06-17 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0013_remove_estudiante_aula'),
        ('matriculas', '0009_alter_matricula_periodo_academico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='competencias', to='academico.area')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['area', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo_matricula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='periodos_evaluacion', to='matriculas.periodoacademico')),
            ],
            options={
                'verbose_name': 'Periodo de Evaluación',
                'verbose_name_plural': 'Periodos de Evaluación',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('AD', 'AD'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='estudiantes.estudiante')),
                ('docente_evaluador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='calificaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='calificaciones', to='academico.competencia')),
                ('periodo_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='calificaciones', to='academico.periodoevaluacion')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('alumno', 'competencia', 'periodo_evaluacion')},
            },
        ),
        migrations.CreateModel(
            name='Apreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apreciaciones', to='estudiantes.estudiante')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='apreciaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('periodo_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='apreciaciones', to='academico.periodoevaluacion')),
            ],
            options={
                'verbose_name': 'Apreciación',
                'verbose_name_plural': 'Apreciaciones',
                'unique_together': {('alumno', 'periodo_evaluacion')},
            },
        ),
    ]
