# Generated by Django 6.0.4 on 2026-06-18 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('estudiantes', '0013_remove_estudiante_aula'),
        ('matriculas', '0009_alter_matricula_periodo_academico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones_docentes', to='academico.area')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones_docentes', to='estudiantes.aula')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones_academicas', to=settings.AUTH_USER_MODEL)),
                ('periodo_matricula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones_docentes', to='matriculas.periodoacademico')),
            ],
            options={
                'verbose_name': 'Asignación Docente',
                'verbose_name_plural': 'Asignaciones Docentes',
                'unique_together': {('docente', 'aula', 'area', 'periodo_matricula')},
            },
        ),
    ]
