# Generated by Django 6.0.4 on 2026-09-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_asignaciondocente'),
        ('estudiantes', '0013_remove_estudiante_aula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apreciacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='apreciacion',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='apreciaciones', to='academico.area'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='apreciacion',
            unique_together={('alumno', 'periodo_evaluacion', 'area')},
        ),
    ]
