# Generated by Django 6.0.4 on 2026-05-22 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_alter_apoderado_dni'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apoderado_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='estudiantes.apoderado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('directora', 'Directora'), ('administradora', 'Administradora'), ('apoderado', 'Apoderado')], max_length=20),
        ),
    ]
