# Generated by Django 6.0.4 on 2026-05-22 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_apoderado_rel_alter_usuario_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='role',
        ),
    ]
