# Generated by Django 6.0.4 on 2026-05-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='first_login',
            field=models.BooleanField(default=True, verbose_name='Primer inicio de sesión'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='Es Apoderado'),
        ),
    ]
