# Generated by Django 6.0.4 on 2026-05-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_alter_apoderado_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
