# Generated by Django 6.0.4 on 2026-05-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_alter_apoderado_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='codigo_estudiante',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
