# Generated by Django 6.0.4 on 2026-05-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_alter_apoderado_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='codido_estudiante',
            field=models.CharField(default='ESTU0000', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
