# Generated by Django 6.0.4 on 2026-05-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_estudiante_codido_estudiante_estudiante_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codido_estudiante',
            field=models.CharField(default='ESTU0000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(default='00000000', max_length=8, unique=True),
        ),
    ]
