# Generated by Django 6.0.4 on 2026-05-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_estudiante_codigo_estudiante_estudiante_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
