# Generated by Django 6.0.4 on 2026-05-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_alter_estudiante_codido_estudiante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='codido_estudiante',
            new_name='codigo_estudiante',
        ),
    ]
