# Generated by Django 6.0.4 on 2026-05-26 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_alter_apoderado_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='estudiantes.apoderado'),
        ),
    ]
