# Generated by Django 6.0.4 on 2026-05-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_alter_estudiante_apoderado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.aula'),
        ),
    ]
