# Generated by Django 6.0.4 on 2026-06-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0010_alter_estudiante_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apoderado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='estudiantes.apoderado'),
        ),
    ]
