# Generated by Django 6.0.4 on 2026-06-08 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0011_alter_estudiante_apoderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='apoderado',
        ),
        migrations.CreateModel(
            name='ApoderadoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor'), ('ABUELO', 'Abuelo'), ('OTRO', 'Otro')], max_length=20)),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='estudiantes.apoderado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoderados', to='estudiantes.estudiante')),
            ],
            options={
                'unique_together': {('apoderado', 'estudiante')},
            },
        ),
    ]
