# Generated by Django 6.0.4 on 2026-06-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_remove_estudiante_apoderado_apoderadoestudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='aula',
        ),
    ]
