# Generated by Django 6.0.4 on 2026-06-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_alter_estudiante_apoderado'),
        ('matriculas', '0006_periodoacademico_matricula_periodo_academico'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matricula',
            name='unique_matricula_anio',
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('alumno', 'periodo_academico'), name='unique_matricula_periodo', violation_error_message='El alumno ya está matriculado en este período académico'),
        ),
    ]
