# Generated by Django 6.0.4 on 2026-06-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_alter_estudiante_apoderado'),
        ('matriculas', '0007_remove_matricula_unique_matricula_anio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-fecha_matricula'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.RemoveIndex(
            model_name='matricula',
            name='matriculas__anio_05cfab_idx',
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['periodo_academico'], name='matriculas__periodo_59be65_idx'),
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='anio',
        ),
    ]
