# Generated by Django 6.0.4 on 2026-06-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0008_alter_matricula_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='periodo_academico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='matriculas', to='matriculas.periodoacademico'),
        ),
    ]
